# This workflow will build a .NET Core app using .NET 10 Ubuntu.
#
name: Build .NET Solution (ASP.Net Core)

env:
  DOTNET_VERSION: "10.0"                            # Set this to the .NET Core version you want to use
  Local_Sharp_AI_Artifacts_Name: "local_sharp_ai_artifacts" # Name of the artifact produced by the build job

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: CI (.NET 10)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Test with dotnet
        run: dotnet test --configuration Release
      
      - name: Publish with dotnet
        run: dotnet publish ./Local.Sharp.AI.sln --configuration Release --output artifacts/

      - name: Upload published artifacts under artifacts/
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.Local_Sharp_AI_Artifacts_Name }}
          path: artifacts/
  
  deploy-dev:
    name: CD (Deploy to Azure Web App .NET 10 (Development Environment))
    runs-on: ubuntu-latest
    needs: build

    env:
      AZURE_WEBAPP_NAME: local-sharp-ai-azure-webapp
      AZURE_WEBAPP_PACKAGE_PATH: 'artifacts/'

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Download published artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.Local_Sharp_AI_Artifacts_Name }}
          path: artifacts/

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Development'
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
