# This workflow will build a .NET Core app using .NET 10 Ubuntu.
#
name: Build .NET Solution (ASP.Net Core)

env:
  DOTNET_VERSION: "10.0"                            # Set this to the .NET Core version you want to use

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: PR Verify (Build .NET Core Solution)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore with dotnet
        run: dotnet restore ./Local.Sharp.AI.sln
        
      - name: Format code with dotnet format
        run: dotnet format --verify-no-changes

      - name: Build with dotnet
        run: dotnet build --configuration Release
